---
apiVersion: v1
kind: Namespace
metadata:
  name: sapper-kube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapper-kube
  namespace: sapper-kube
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sapper-kube
      app.kubernetes.io/name: sapper-kube
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sapper-kube
        app.kubernetes.io/name: sapper-kube
    spec:
      containers:
      - name: sapper-kube
        image: acim/sapper-kube
        imagePullPolicy: Always